// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0oIvcGCap2sPSzOZbvZCaACwoWdNH7I',
    appId: '1:231792680198:web:658a7101e01eb58393d287',
    messagingSenderId: '231792680198',
    projectId: 'speakercontrol-d2581',
    authDomain: 'speakercontrol-d2581.firebaseapp.com',
    storageBucket: 'speakercontrol-d2581.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Irc6LGyNpY9rFJfmLGb-3ISKryUtT-g',
    appId: '1:231792680198:android:49a1db96b3ec76be93d287',
    messagingSenderId: '231792680198',
    projectId: 'speakercontrol-d2581',
    storageBucket: 'speakercontrol-d2581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjy4mnKp6YKaj53mgtImpayuJSVh3Fgc',
    appId: '1:231792680198:ios:b57efd3f2fee019693d287',
    messagingSenderId: '231792680198',
    projectId: 'speakercontrol-d2581',
    storageBucket: 'speakercontrol-d2581.appspot.com',
    iosBundleId: 'com.example.speakerControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjy4mnKp6YKaj53mgtImpayuJSVh3Fgc',
    appId: '1:231792680198:ios:b57efd3f2fee019693d287',
    messagingSenderId: '231792680198',
    projectId: 'speakercontrol-d2581',
    storageBucket: 'speakercontrol-d2581.appspot.com',
    iosBundleId: 'com.example.speakerControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX0oIvcGCap2sPSzOZbvZCaACwoWdNH7I',
    appId: '1:231792680198:web:44cfd7386e78cde493d287',
    messagingSenderId: '231792680198',
    projectId: 'speakercontrol-d2581',
    authDomain: 'speakercontrol-d2581.firebaseapp.com',
    storageBucket: 'speakercontrol-d2581.appspot.com',
  );
}
